<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ОсобистаІнформаціяДляЛікаря.aspx.cs" Inherits="test.ОсобистаІнформаціяДляЛікаря" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 273px;
        }
        .auto-style3 {
            width: 328px;
        }
        .auto-style4 {
            margin-left: 1px;
        }
        .auto-style5 {
            width: 150px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Button ID="Button2" runat="server" Text="Створити картку" OnClick="Button2_Click" />
            <asp:Button ID="Button3" runat="server" Text="Пошук" OnClick="Button3_Click" />
            <asp:Button ID="Button4" runat="server" OnClick="Button4_Click" Text="Вийти" />
        </div>
        <div>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:EMR %>" SelectCommand="SELECT * FROM [Patient] WHERE ([ID] = @ID)">
                <SelectParameters>
                    <asp:QueryStringParameter Name="ID" QueryStringField="ID" Type="Int32" />
                </SelectParameters>
            </asp:SqlDataSource>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ID" DataSourceID="SqlDataSource1" CellPadding="4" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                    <asp:BoundField DataField="Surname" HeaderText="Прізвище" SortExpression="Surname" />
                    <asp:BoundField DataField="Name" HeaderText="Ім'я" SortExpression="Name" />
                    <asp:BoundField DataField="Father_name" HeaderText="По-батькові" SortExpression="Father_name" />
                    <asp:BoundField DataField="Sex" HeaderText="Стать" SortExpression="Sex" />
                    <asp:BoundField DataField="Birthday" HeaderText="Дата народження" SortExpression="Birthday" />
                    <asp:BoundField DataField="Blood" HeaderText="Кров" SortExpression="Blood" />
                    <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
                    <asp:BoundField DataField="Street" HeaderText="Вулиця" SortExpression="Street" />
                    <asp:BoundField DataField="House" HeaderText="Будинок" SortExpression="House" />
                    <asp:BoundField DataField="Apartment" HeaderText="Квартира" SortExpression="Apartment" />
                    <asp:BoundField DataField="Telephone" HeaderText="Номер телефону" SortExpression="Telephone" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
        </div>
        <div style="margin-left: 40px">
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:EMR %>" SelectCommand="SELECT * FROM [Chek] WHERE ([patient] = @patient)" UpdateCommand =" UPDATE [Chek] SET [date]=@date, [complaints]=@complaints, [conclusion]=@conclusion, [doctor]=@doctor, [patient]=@patient, [medical_centre]=@medical_centre, [notes]=@notes where [appointment]=@appointment"  DeleteCommand="DELETE FROM [Chek] where [appointment]=@appointment">
                <SelectParameters>
                    <asp:QueryStringParameter Name="patient" QueryStringField="ID" Type="Int32" />
                </SelectParameters>
                <DeleteParameters>
                    <%-- <asp:QueryStringParameter Name="patient" QueryStringField="appointment" Type="Int32" /> --%>
                    <asp:Parameter Name="appointment" Type="Int32" />
                </DeleteParameters>
            </asp:SqlDataSource>
            <asp:GridView ID="GridView2" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource2" AutoGenerateColumns="False" DataKeyNames="appointment" CellPadding="4" ForeColor="#333333" GridLines="None" >
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="appointment" HeaderText="appointment" SortExpression="appointment" Visible="False" />
                    <asp:BoundField DataField="date" HeaderText="Дата прийому" SortExpression="date" />
                    <asp:BoundField DataField="complaints" HeaderText="Скарги" SortExpression="complaints" />
                    <asp:BoundField DataField="conclusion" HeaderText="Заключення" SortExpression="conclusion" />
                    <asp:BoundField DataField="doctor" HeaderText="Лікар" SortExpression="doctor" />
                    <asp:BoundField DataField="patient" HeaderText="Пацієнт" SortExpression="patient" />
                    <asp:BoundField DataField="medical_centre" HeaderText="Медичний заклад" SortExpression="medical_centre" />
                    <asp:BoundField DataField="notes" HeaderText="Примітки" SortExpression="notes" />
                </Columns>
           
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
           
                </asp:GridView>

            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Додати" />
            <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:EMR %>" SelectCommand="SELECT [ID], [Surname] FROM [Doctor]"></asp:SqlDataSource>
            <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:EMR %>" SelectCommand="SELECT [ID], [Name] FROM [MedicalCentre]"></asp:SqlDataSource>
            <br />
            <div>
                <table class="auto-style1">
                    <tr>
                        <td class="auto-style5">Дата</td>
                        <td class="auto-style3">
            <asp:TextBox ID="TextBox1" runat="server" MaxLength="10" TextMode="Date" Width="170px"></asp:TextBox>
                        </td>
                        <td class="auto-style2">Лікар</td>
                        <td>
            <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource3" DataTextField="Surname" DataValueField="ID">
            </asp:DropDownList>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style5">Скарги</td>
                        <td class="auto-style3">
            <asp:TextBox ID="TextBox2" runat="server" CssClass="auto-style4" TextMode="MultiLine"></asp:TextBox>
                        </td>
                        <td class="auto-style2">Пацієнт(ID)</td>
                        <td>
            <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style5">Заключення</td>
                        <td class="auto-style3">
            <asp:TextBox ID="TextBox3" runat="server" TextMode="MultiLine"></asp:TextBox>
                        </td>
                        <td class="auto-style2">Медичний заклад</td>
                        <td>
            <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSource4" DataTextField="Name" DataValueField="ID">
            </asp:DropDownList>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style5">&nbsp;</td>
                        <td class="auto-style3">&nbsp;</td>
                        <td class="auto-style2">Примітки</td>
                        <td>
            <asp:TextBox ID="TextBox5" runat="server" TextMode="MultiLine"></asp:TextBox>
                        </td>
                    </tr>
                </table>
            </div>
            <br />

            <asp:Table ID="Table1" runat="server">

            </asp:Table>

        </div>
    </form>
</body>
</html>
